piecedata = [
    {
        'name': 'Pawn',
        'value': 1,
        'role': 'Frontrank',
        'promotion': 'Queen',
        'img': 'white_pawn.png',
        'movements': {
            (0, 0, 'start'): [(0, 1, 'move'), (-1, 1, 'capture'), (1, 1, 'capture')],
            (0, 1, 'move'): [(0, 2, 'move')]
        },
        'newmovements': {
            (0, 0, 'start'): [(0, 1, 'move'), (-1, 1, 'capture'), (1, 1, 'capture')]
        }
    },
    {
        'name': 'Knight',
        'value': 3,
        'role': 'Backrank',
        'promotion': None,
        'img': 'white_knight.png',
        'movements': {
            (0, 0, 'start'): [(2, 1, 'attack'), (1, 2, 'attack'), (-1, 2, 'attack'), (-2, 1, 'attack'),
                              (-2, -1, 'attack'), (-1, -2, 'attack'), (1, -2, 'attack'), (2, -1, 'attack')]
        },
        'newmovements': None
    },
    {
        'name': 'Bishop',
        'value': 3,
        'role': 'Backrank',
        'promotion': None,
        'img': 'white_bishop.png',
        'movements': {
            (0, 0, 'start'): [(1, 1, 'attack'), (-1, 1, 'attack'), (1, -1, 'attack'), (-1, -1, 'attack')],
            (1, 1, 'attack'): [(2, 2, 'attack')],
            (2, 2, 'attack'): [(3, 3, 'attack')],
            (3, 3, 'attack'): [(4, 4, 'attack')],
            (4, 4, 'attack'): [(5, 5, 'attack')],
            (5, 5, 'attack'): [(6, 6, 'attack')],
            (6, 6, 'attack'): [(7, 7, 'attack')],
            (-1, 1, 'attack'): [(-2, 2, 'attack')],
            (-2, 2, 'attack'): [(-3, 3, 'attack')],
            (-3, 3, 'attack'): [(-4, 4, 'attack')],
            (-4, 4, 'attack'): [(-5, 5, 'attack')],
            (-5, 5, 'attack'): [(-6, 6, 'attack')],
            (-6, 6, 'attack'): [(-7, 7, 'attack')],
            (1, -1, 'attack'): [(2, -2, 'attack')],
            (2, -2, 'attack'): [(3, -3, 'attack')],
            (3, -3, 'attack'): [(4, -4, 'attack')],
            (4, -4, 'attack'): [(5, -5, 'attack')],
            (5, -5, 'attack'): [(6, -6, 'attack')],
            (6, -6, 'attack'): [(7, -7, 'attack')],
            (-1, -1, 'attack'): [(-2, -2, 'attack')],
            (-2, -2, 'attack'): [(-3, -3, 'attack')],
            (-3, -3, 'attack'): [(-4, -4, 'attack')],
            (-4, -4, 'attack'): [(-5, -5, 'attack')],
            (-5, -5, 'attack'): [(-6, -6, 'attack')],
            (-6, -6, 'attack'): [(-7, -7, 'attack')],
        },
        'newmovements': None
    },
    {
        'name': 'Rook',
        'value': 5,
        'role': 'Backrank',
        'promotion': None,
        'img': 'white_rook.png',
        'movements': {
            (0, 0, 'start'): [(1, 0, 'attack'), (-1, 0, 'attack'), (0, 1, 'attack'), (0, -1, 'attack')],
            (1, 0, 'attack'): [(2, 0, 'attack')],
            (2, 0, 'attack'): [(3, 0, 'attack')],
            (3, 0, 'attack'): [(4, 0, 'attack')],
            (4, 0, 'attack'): [(5, 0, 'attack')],
            (5, 0, 'attack'): [(6, 0, 'attack')],
            (6, 0, 'attack'): [(7, 0, 'attack')],
            (-1, 0, 'attack'): [(-2, 0, 'attack')],
            (-2, 0, 'attack'): [(-3, 0, 'attack')],
            (-3, 0, 'attack'): [(-4, 0, 'attack')],
            (-4, 0, 'attack'): [(-5, 0, 'attack')],
            (-5, 0, 'attack'): [(-6, 0, 'attack')],
            (-6, 0, 'attack'): [(-7, 0, 'attack')],
            (0, 1, 'attack'): [(0, 2, 'attack')],
            (0, 2, 'attack'): [(0, 3, 'attack')],
            (0, 3, 'attack'): [(0, 4, 'attack')],
            (0, 4, 'attack'): [(0, 5, 'attack')],
            (0, 5, 'attack'): [(0, 6, 'attack')],
            (0, 6, 'attack'): [(0, 7, 'attack')],
            (0, -1, 'attack'): [(0, -2, 'attack')],
            (0, -2, 'attack'): [(0, -3, 'attack')],
            (0, -3, 'attack'): [(0, -4, 'attack')],
            (0, -4, 'attack'): [(0, -5, 'attack')],
            (0, -5, 'attack'): [(0, -6, 'attack')],
            (0, -6, 'attack'): [(0, -7, 'attack')],
        },
        'newmovements': None
    },
    {
        'name': 'Queen',
        'value': 9,
        'role': 'Backrank',
        'promotion': None,
        'img': 'white_queen.png',
        'movements': {
            (0, 0, 'start'): [(1, 0, 'attack'), (-1, 0, 'attack'), (0, 1, 'attack'), (0, -1, 'attack'),
                              (1, 1, 'attack'), (-1, 1, 'attack'), (1, -1, 'attack'), (-1, -1, 'attack')],
            (1, 0, 'attack'): [(2, 0, 'attack')],
            (2, 0, 'attack'): [(3, 0, 'attack')],
            (3, 0, 'attack'): [(4, 0, 'attack')],
            (4, 0, 'attack'): [(5, 0, 'attack')],
            (5, 0, 'attack'): [(6, 0, 'attack')],
            (6, 0, 'attack'): [(7, 0, 'attack')],
            (-1, 0, 'attack'): [(-2, 0, 'attack')],
            (-2, 0, 'attack'): [(-3, 0, 'attack')],
            (-3, 0, 'attack'): [(-4, 0, 'attack')],
            (-4, 0, 'attack'): [(-5, 0, 'attack')],
            (-5, 0, 'attack'): [(-6, 0, 'attack')],
            (-6, 0, 'attack'): [(-7, 0, 'attack')],
            (0, 1, 'attack'): [(0, 2, 'attack')],
            (0, 2, 'attack'): [(0, 3, 'attack')],
            (0, 3, 'attack'): [(0, 4, 'attack')],
            (0, 4, 'attack'): [(0, 5, 'attack')],
            (0, 5, 'attack'): [(0, 6, 'attack')],
            (0, 6, 'attack'): [(0, 7, 'attack')],
            (0, -1, 'attack'): [(0, -2, 'attack')],
            (0, -2, 'attack'): [(0, -3, 'attack')],
            (0, -3, 'attack'): [(0, -4, 'attack')],
            (0, -4, 'attack'): [(0, -5, 'attack')],
            (0, -5, 'attack'): [(0, -6, 'attack')],
            (0, -6, 'attack'): [(0, -7, 'attack')],
            (1, 1, 'attack'): [(2, 2, 'attack')],
            (2, 2, 'attack'): [(3, 3, 'attack')],
            (3, 3, 'attack'): [(4, 4, 'attack')],
            (4, 4, 'attack'): [(5, 5, 'attack')],
            (5, 5, 'attack'): [(6, 6, 'attack')],
            (6, 6, 'attack'): [(7, 7, 'attack')],
            (-1, 1, 'attack'): [(-2, 2, 'attack')],
            (-2, 2, 'attack'): [(-3, 3, 'attack')],
            (-3, 3, 'attack'): [(-4, 4, 'attack')],
            (-4, 4, 'attack'): [(-5, 5, 'attack')],
            (-5, 5, 'attack'): [(-6, 6, 'attack')],
            (-6, 6, 'attack'): [(-7, 7, 'attack')],
            (1, -1, 'attack'): [(2, -2, 'attack')],
            (2, -2, 'attack'): [(3, -3, 'attack')],
            (3, -3, 'attack'): [(4, -4, 'attack')],
            (4, -4, 'attack'): [(5, -5, 'attack')],
            (5, -5, 'attack'): [(6, -6, 'attack')],
            (6, -6, 'attack'): [(7, -7, 'attack')],
            (-1, -1, 'attack'): [(-2, -2, 'attack')],
            (-2, -2, 'attack'): [(-3, -3, 'attack')],
            (-3, -3, 'attack'): [(-4, -4, 'attack')],
            (-4, -4, 'attack'): [(-5, -5, 'attack')],
            (-5, -5, 'attack'): [(-6, -6, 'attack')],
            (-6, -6, 'attack'): [(-7, -7, 'attack')],
        },
        'newmovements': None
    },
    {
        'name': 'King',
        'value': 0,
        'role': 'Leader',
        'promotion': None,
        'img': 'white_king.png',
        'movements': {
            (0, 0, 'start'): [(1, 0, 'attack'), (-1, 0, 'attack'), (0, 1, 'attack'), (0, -1, 'attack'),
                              (1, 1, 'attack'), (-1, 1, 'attack'), (1, -1, 'attack'), (-1, -1, 'attack')]
        },
        'newmovements': None
    }
]